global:
  smtp_smarthost: 'smtp.exemplo.com:587'
  smtp_from: 'alertas@exemplo.com'
  smtp_auth_username: 'usuario'
  smtp_auth_password: 'senha'
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'default'

  routes:
    - match:
        severity: critical
      receiver: 'email-and-telegram'

receivers:
  - name: 'email-and-telegram'
    email_configs:
      - to: 'gustavodcdamas@gmail.com, kadegiovani@gmail.com, giovanikade@hotmail.com'
        send_resolved: true
    telegram_configs:
      - send_resolved: true
        bot_token: '<SEU_TOKEN>'
        chat_id: '<SEU_CHAT_ID>'

