version: "3.8"
#Para servidor Linux
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/sites-available:/etc/nginx/sites-available
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/letsencrypt:/etc/letsencrypt
        - ./public:/var/www/public
    networks:
      - net_swarm
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 20M
      restart_policy:
        condition: on-failure

networks:
  net_swarm:
    external: true
