version: '3.8'
services:
    nginx:
        image: nginx:latest
        name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available:/etc/nginx/sites-available
            - /etc/ssl/certs/cuei.com.br.crt:/etc/ssl/certs/cuei.com.br.crt  # Mount SSL certificate
            - /etc/ssl/private/cuei.com.br.key:/etc/ssl/private/cuei.com.br.key 
            - /etc/ssl/private/cuei.com.br.pem:/etc/ssl/private/cuei.com.br.pem
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/letsencrypt:/etc/letsencrypt
            - ./public:/var/www/public
            - ./logs:/var/log/nginx/
        networks:
            - net_swarm
        deploy:
            replicas: 1
            resources:
            limits:
                cpus: "1"
                memory: 1G
            reservations:
                cpus: "0.25"
                memory: 512M
            restart_policy:
                condition: on-failure

networks:
  net_swarm:
    external: true
