version: "3.7"
services:
  n8n:
    image: n8nio/n8n:latest
    env_file: .env
    command: start
    networks:
      - net_geral
      - net_swarm
    volumes:
      - n8n:/home/node/.n8n
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
      restart_policy:
        condition: on-failure
  n8n_webhook:
    image: n8nio/n8n:latest
    env_file: .env
    command: webhook
    networks:
      - net_geral
      - net_swarm
    volumes:
      - n8n:/home/node/.n8n
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 256M
      restart_policy:
        condition: on-failure
  n8n_worker:
    image: n8nio/n8n:latest
    env_file: .env
    command: worker --concurrency=10
    networks:
      - net_geral
      - net_swarm
    volumes:
      - n8n:/home/node/.n8n
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
      restart_policy:
        condition: on-failure
networks:
  net_swarm:
    external: true
    attachable: true
  net_geral:
    attachable: true
    external: true

volumes:
  n8n:
    external: true