version: "3.7"

services:
  n8n_editor:
    image: n8nio/n8n:latest
    env_file: .env
    name: n8n
    command: start
    networks:
      - net_geral
      - net_swarm
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
      restart_policy:
        condition: on-failure
  n8n_webhook:
    image: n8nio/n8n:latest
    name: n8n_webhook
    env_file: .env
    command: webhook
    networks:
      - net_geral
      - net_swarm
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
      restart_policy:
        condition: on-failure
  n8n_worker:
    image: n8nio/n8n:latest
    name: n8n_worker
    env_file: .env
    command: worker --concurrency=10
    networks:
      - net_geral
      - net_swarm
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
      restart_policy:
        condition: on-failure
networks:
  net_swarm:
    external: true
    attachable: true
  net_geral:
    driver: bridge
    external: true

volumes:
  n8n:
    external: true
    name: n8n