version: "3.7"
services:
  mysql:
    image: mysql/mysql-server:latest
    env_file: .env
    networks:
      - net_geral
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
      restart_policy:
        condition: on-failure

volumes:
  mysql-data:
    external: true

networks:
  net_geral:
    driver: bridge
    external: true
