version: "3.8"

services:
  redis:
    image: redis:latest
    env_file: .env
    command: ["redis-server", "--appendonly", "yes", "--port", "6379", "--requirepass", "Mesa12Chuveiro67"]
    networks:
      - net_geral
    volumes:
      - ./redis_data:/data
    deploy:
      labels:
        - "com.docker.stack.namespace=redis"
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
      restart_policy:
        condition: on-failure

networks:
  net_geral:
    attachable: true
    external: true