version: "3.8"

services:
  postgres:
    image: postgres:16.4
    env_file: .env
    command: [postgres, --max_connections=100]
    networks:
      - net_geral
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    deploy:
      labels:
        - "com.docker.stack.namespace=postgres"
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
      restart_policy:
        condition: on-failure

networks:
  net_geral:
    attachable: true
    external: true