version: "3"

services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    env_file: .env    
    volumes:
      - nextcloud:/var/www/html
      - nextcloud_config:/config
      - nextcloud_data:/data
    ports:
      - 8081:443
    networks:
      - net_geral
      - net_swarm
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
      restart_policy:
        condition: on-failure
volumes:
  nextcloud:
    external: true
  nextcloud_config:
    external: true
  nextcloud_data:
    external: true

networks:
  net_swarm:
    external: true
    attachable: true
  net_geral:
    attachable: true
    external: true
