version: '3.7'
services:
  evolution:
    image: atendai/evolution-api:v2.1.1
    env_file: .env
    networks:
      - net_swarm
      - net_geral
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    ports:
      - 8080:8080
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
      restart_policy:
        condition: on-failure
volumes:
  evolution_instances:
    external: true
  evolution_store:
    external: true

networks:
  net_swarm:
    external: true
    attachable: true
  net_geral:
    attachable: true
    external: true