version: '3.7'
services:
  evolution2:
    name: evolution2
    image: atendai/evolution-api:v2.2.2
    restart: always
    env_file: .env
    networks:
      - net_swarm
      - net_geral
    ports:
      - 8080:8080
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
      restart_policy:
        condition: on-failure

networks:
  net_swarm:
    external: true
    attachable: true
  net_geral:
    driver: bridge
    external: true