version: '3.8'

services:

  #postgres:
   # container_name: odoo-postgres
   # image: postgres:14.1-alpine
   # networks:
   #   - web
    #ports:
    #  - 5432:5432
    #environment:
    #  POSTGRES_DB: postgres
    #  POSTGRES_USER: odoo
    #  POSTGRES_PASSWORD: secret
    #volumes:
    #  - ./postgres-data:/var/lib/postgresql/data
    #restart: always
  odoo:
    name: odoo
    env_file: .env
    image: odoo:16
    networks:
      - web
    ports:
      - 9072:8072
      - 8069:8069
    volumes:
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./data:/var/lib/odoo
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
      restart_policy:
        condition: on-failure

networks:
  net_swarm:
    external: true
    attachable: true
  net_geral:
    driver: bridge
    external: true
